# Generated by Django 4.2 on 2023-04-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_remove_customer_username_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
