# Generated by Django 4.2 on 2023-04-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_customer_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuscleGroupExo',
            new_name='Exercice',
        ),
    ]
