# Generated by Django 4.2 on 2023-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_alter_customer_address_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='civility',
            field=models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame')], max_length=10, null=True),
        ),
    ]
