# Generated by Django 4.2 on 2023-04-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_rename_musclegroupexo_exercice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercice',
            new_name='Exercise',
        ),
    ]
