# Generated by Django 4.2 on 2023-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_rename_exercice_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Warm-up',
                'verbose_name_plural': 'Warm-ups',
            },
        ),
    ]
