# Generated by Django 4.2 on 2023-04-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_warmup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarmUp',
            new_name='Hiit',
        ),
        migrations.AlterModelOptions(
            name='hiit',
            options={'verbose_name': 'Hiit', 'verbose_name_plural': 'Hiit'},
        ),
    ]
