# Generated by Django 4.2 on 2023-04-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_rename_warmup_hiit_alter_hiit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiit',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.musclegroup'),
        ),
    ]
