# Generated by Django 4.2 on 2023-04-22 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_hiit_muscle_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiit',
            options={'ordering': ['name'], 'verbose_name': 'Hiit', 'verbose_name_plural': 'Hiit'},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ['name'], 'verbose_name': 'Muscle', 'verbose_name_plural': 'Muscles'},
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
