# Generated by Django 4.2 on 2023-04-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_programtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.programtype'),
        ),
    ]
