# Generated by Django 4.2 on 2023-04-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_program_program_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramHiit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('set', models.IntegerField(default=0, verbose_name='Sets')),
                ('pause', models.CharField(choices=[('D', '20s ON / 20s OFF'), ('I', '25s ON / 15s OFF'), ('A', '30s ON / 10s OFF')], max_length=2)),
                ('level', models.CharField(choices=[('D', '2mins'), ('I', '1min30'), ('A', '1min')], max_length=2)),
            ],
        ),
    ]
