# Generated by Django 4.2 on 2023-04-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_programhiit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiit',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.programhiit'),
        ),
        migrations.AlterField(
            model_name='programhiit',
            name='level',
            field=models.CharField(choices=[('D', '20s ON / 20s OFF'), ('I', '25s ON / 15s OFF'), ('A', '30s ON / 10s OFF')], max_length=2),
        ),
        migrations.AlterField(
            model_name='programhiit',
            name='pause',
            field=models.CharField(choices=[('D', '2mins'), ('I', '1min30'), ('A', '1min')], max_length=2),
        ),
    ]
