# Generated by Django 4.2 on 2023-04-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Hiit', 'Hiit'), ('Bodybuilding', 'Bodybuilding')], default='Hiit', max_length=15),
        ),
    ]
