# Generated by Django 4.2 on 2023-04-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_alter_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='programhiit',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.exercise'),
        ),
    ]
