# Generated by Django 4.2 on 2023-04-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_programhiit_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programhiit',
            name='exercise',
        ),
    ]
