# Generated by Django 4.2 on 2023-04-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_remove_programhiit_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog_hiit',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exercise'),
        ),
    ]
