# Generated by Django 4.2 on 2023-04-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_prog_hiit_exercice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prog_hiit',
            old_name='exercice',
            new_name='exercise',
        ),
    ]
