# Generated by Django 4.2 on 2023-04-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_prog_hiit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgExoHiit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Hiit',
            new_name='ExoHiit',
        ),
        migrations.DeleteModel(
            name='prog_hiit',
        ),
        migrations.AddField(
            model_name='progexohiit',
            name='exo_hiit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exohiit'),
        ),
        migrations.AddField(
            model_name='progexohiit',
            name='program_hiit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.programhiit'),
        ),
    ]
