# Generated by Django 4.2 on 2023-04-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_alter_exercise_options_alter_exohiit_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='ExoBody',
        ),
    ]
