# Generated by Django 4.2 on 2023-04-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_rename_exercise_exobody'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramType',
            new_name='PType',
        ),
    ]
