# Generated by Django 4.2 on 2023-04-22 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0027_rename_name_programbody_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programbody',
            name='pause',
            field=models.CharField(choices=[('D', '2mins'), ('I', '1min30'), ('A', '1min')], default='A', max_length=2),
        ),
        migrations.CreateModel(
            name='ProgExoBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exo_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exobody')),
                ('program_Body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.programbody')),
            ],
            options={
                'verbose_name': 'Body-ProgramExo',
                'verbose_name_plural': 'Body-Programs-Exos',
            },
        ),
    ]
