# Generated by Django 4.2 on 2023-04-22 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0028_alter_programbody_pause_progexobody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('set', models.IntegerField(default=0, null=True, verbose_name='Sets')),
                ('rep', models.IntegerField(default=0, null=True, verbose_name='Reps')),
                ('pause', models.CharField(choices=[('D', '2mins'), ('I', '1min30'), ('A', '1min')], default='A', max_length=2)),
                ('exo_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exobody')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.ptype')),
            ],
        ),
    ]
