# Generated by Django 4.2 on 2023-04-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0029_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbody',
            name='exo_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exobody'),
        ),
    ]
