# Generated by Django 4.2 on 2023-04-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0030_programbody_exo_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='exo_body',
        ),
        migrations.RemoveField(
            model_name='program',
            name='pause',
        ),
        migrations.RemoveField(
            model_name='program',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='program',
            name='set',
        ),
        migrations.RemoveField(
            model_name='programbody',
            name='title',
        ),
        migrations.AddField(
            model_name='programbody',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='backoffice.program'),
        ),
    ]
