# Generated by Django 4.2 on 2023-04-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0031_remove_program_exo_body_remove_program_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbody',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.musclegroup'),
        ),
        migrations.AddField(
            model_name='programbody',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
