# Generated by Django 4.2 on 2023-04-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0032_programbody_muscle_group_programbody_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField(default=0, null=True, verbose_name='Sets')),
                ('rep', models.IntegerField(default=0, null=True, verbose_name='Reps')),
                ('pause', models.CharField(choices=[('D', '2mins'), ('I', '1min30'), ('A', '1min')], default='A', max_length=2)),
                ('exo_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exobody')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='backoffice.program')),
            ],
            options={
                'verbose_name': 'Body-Program',
                'verbose_name_plural': 'Body-Programs',
            },
        ),
        migrations.AlterField(
            model_name='progexobody',
            name='program_Body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.formbody'),
        ),
        migrations.DeleteModel(
            name='ProgramBody',
        ),
    ]
