# Generated by Django 4.2 on 2023-04-22 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0033_formbody_alter_progexobody_program_body_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='ProgramBody',
        ),
        migrations.RemoveField(
            model_name='formbody',
            name='program',
        ),
        migrations.AddField(
            model_name='formbody',
            name='program_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_body', to='backoffice.programbody'),
        ),
    ]
