# Generated by Django 4.2 on 2023-04-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0034_rename_program_programbody_remove_formbody_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formbody',
            options={'verbose_name': 'Body-Form', 'verbose_name_plural': 'Body-Forms'},
        ),
        migrations.AlterModelOptions(
            name='programbody',
            options={'verbose_name': 'Body-Program', 'verbose_name_plural': 'Body-Programs'},
        ),
        migrations.DeleteModel(
            name='ProgExoBody',
        ),
    ]
