# Generated by Django 4.2 on 2023-04-23 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0035_alter_formbody_options_alter_programbody_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programbody',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formbody',
            name='pause',
            field=models.CharField(choices=[('AA', '30s'), ('A', '1min'), ('I', '1min30'), ('D', '2mins')], default='A', max_length=2),
        ),
    ]
