# Generated by Django 4.2 on 2023-04-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0036_programbody_customer_alter_formbody_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbody',
            name='type',
            field=models.CharField(choices=[('WARMUP', 'Warm-up'), ('WOD', 'Wod')], default='WOD', max_length=10),
        ),
    ]
