# Generated by Django 4.2 on 2023-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0037_formbody_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbody',
            name='rep',
            field=models.IntegerField(default=10, null=True, verbose_name='Reps'),
        ),
        migrations.AlterField(
            model_name='formbody',
            name='set',
            field=models.IntegerField(default=2, null=True, verbose_name='Sets'),
        ),
        migrations.AlterField(
            model_name='programbody',
            name='program_type',
            field=models.CharField(default='Bodybuilding', editable=False, max_length=100),
        ),
    ]
