# Generated by Django 4.2 on 2023-04-23 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0038_alter_formbody_rep_alter_formbody_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programhiit',
            options={'verbose_name': 'Hiit-Program', 'verbose_name_plural': 'Hiit-Programs'},
        ),
        migrations.AddField(
            model_name='programhiit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programhiit',
            name='program_type',
            field=models.CharField(default='Hiit', max_length=25),
        ),
        migrations.AlterField(
            model_name='formbody',
            name='type',
            field=models.CharField(choices=[('NONE', '---------'), ('WARMUP', 'Warm-up'), ('WOD', 'Wod')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='programbody',
            name='program_type',
            field=models.CharField(default='Bodybuilding', max_length=25),
        ),
    ]
