# Generated by Django 4.2 on 2023-04-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0039_alter_programhiit_options_programhiit_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exohiit',
            options={'verbose_name': 'Hiit-Exo', 'verbose_name_plural': 'Hiit-Exos'},
        ),
        migrations.RemoveField(
            model_name='programhiit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='programhiit',
            name='pause',
        ),
        migrations.RemoveField(
            model_name='programhiit',
            name='set',
        ),
        migrations.CreateModel(
            name='FormHiit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NONE', '---------'), ('WARMUP', 'Warm-up'), ('WOD', 'Wod')], default='NONE', max_length=10)),
                ('set', models.IntegerField(default=2, null=True, verbose_name='Sets')),
                ('rep', models.IntegerField(default=10, null=True, verbose_name='Reps')),
                ('pause', models.CharField(choices=[('AA', '30s'), ('A', '1min'), ('I', '1min30'), ('D', '2mins')], default='A', max_length=2)),
                ('level', models.CharField(choices=[('D', '20s ON / 20s OFF'), ('I', '25s ON / 15s OFF'), ('A', '30s ON / 10s OFF')], default='I', max_length=2)),
                ('exo_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backoffice.exohiit')),
                ('program_hiit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_hiit', to='backoffice.programhiit')),
            ],
            options={
                'verbose_name': 'Hiit-Form',
                'verbose_name_plural': 'Hiit-Forms',
            },
        ),
    ]
