# Generated by Django 4.2 on 2023-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0040_alter_exohiit_options_remove_programhiit_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formhiit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='formhiit',
            name='pause',
        ),
        migrations.RemoveField(
            model_name='formhiit',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='formhiit',
            name='type',
        ),
        migrations.AddField(
            model_name='programhiit',
            name='level',
            field=models.CharField(choices=[('D', '[Débutant] - 20s ON / 20s OFF'), ('I', '[Intermédiaire] - 25s ON / 15s OFF'), ('A', '[Avancé] - 30s ON / 10s OFF')], default='I', max_length=2),
        ),
        migrations.AddField(
            model_name='programhiit',
            name='pause',
            field=models.CharField(choices=[('E', '30s'), ('A', '1min'), ('I', '1min30'), ('D', '2mins')], default='A', max_length=2),
        ),
    ]
