# Generated by Django 4.2 on 2023-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0041_remove_formhiit_level_remove_formhiit_pause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formhiit',
            old_name='exo_body',
            new_name='exo_hiit',
        ),
        migrations.AlterField(
            model_name='programhiit',
            name='level',
            field=models.CharField(choices=[('D', '[Débutant] - 20sec ON / 20sec OFF'), ('I', '[Intermédiaire] - 25sec ON / 15sec OFF'), ('A', '[Avancé] - 30sec ON / 10sec OFF')], default='I', max_length=2),
        ),
        migrations.AlterField(
            model_name='programhiit',
            name='pause',
            field=models.CharField(choices=[('E', '30sec'), ('A', '1min'), ('I', '1min30'), ('D', '2mins')], default='A', max_length=2),
        ),
    ]
