# Generated by Django 4.2 on 2023-04-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0042_rename_exo_body_formhiit_exo_hiit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgExoHiit',
            new_name='ProgramMixte',
        ),
        migrations.AlterModelOptions(
            name='programmixte',
            options={'verbose_name': 'Mixte-Program', 'verbose_name_plural': 'Mixte-Programs'},
        ),
    ]
