# Generated by Django 4.2 on 2023-04-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0043_rename_progexohiit_programmixte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmixte',
            name='exo_hiit',
        ),
        migrations.RemoveField(
            model_name='programmixte',
            name='program_hiit',
        ),
        migrations.AddField(
            model_name='programmixte',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmixte',
            name='program_type',
            field=models.CharField(default='Mixte', max_length=25),
        ),
        migrations.AddField(
            model_name='programmixte',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
